# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=3.0.9
maven_group=net.fneifnox.custommobattributes
archives_base_name=custom-mob-attributes-26.2
# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.13.1+26.2
modmenu_version=20.0.1

# Dependencies
fabric_version=0.158.0+26.2
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.2